# Generated by Django 3.1.7 on 2021-03-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=200, verbose_name='nombres de autor')),
                ('apellidos', models.CharField(max_length=200, verbose_name='apellidos de autor')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram')),
                ('twiter', models.URLField(blank=True, null=True, verbose_name='twiter')),
                ('correo', models.EmailField(max_length=254, verbose_name='correo electronico')),
                ('estado', models.BooleanField(default=True, verbose_name='autor activo/no activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre de la categoria')),
                ('estado', models.BooleanField(default=True, verbose_name='Categori activa /Categoria no activia,')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
    ]
